bsovs/Fall2024-Internships

- README.md
> Add Acoustic

- README.md
> Add Carrier

- README.md
The fall internship for Amazon LLC is re-opened.
> Update Amazon fall internship

- README.md
As title. Minor formatting clean-up, too.
> Closing various positions; adding notes about jobs for US citizens only

- README.md
> Closed Coinbase position

- README.md
> Add Ramp and Cash App

- README.md
Plexus: Added potential U.S. Citizenship or Permanent Residency requirement.
> Chewy, Acoustic, Ramp, Wayfair no longer open

- README.md
> Closed Leidos

- README.md
Added UHG - Optum Technology Development Program Reference URL for Internship and Fulltime Opportunities
> Added UHG - Optum Technology Development Program

- README.md
> Added UHG-Optum US locations

- README.md
[Tesla](https://www.tesla.com/careers/search/job/vehicle-firmware-embedded-systems-engineering-internship-fall-2023-168106?)
> Added Tesla

- README.md
The following companies have been added:
- General Electric
- Johnson & Johnson
- BMW
- Danbury Mission Technologies
- Midmark
- PCAOB (Public Company Accounting Oversight Board)
> Added 6 employers to readme.md

- README.md
Added the following employers:
- NVIDIA
> Added Nvidia to readme.md

- README.md
> Citadel is closed

- README.md
Close: https://github.com/bsovs/Fall2023-Internships/issues/137
> Add anyscale

- README.md
> Close Danbury

- README.md
> issue #127

- README.md
🔒 Closed Jane Street 
🔒 Closed Anyscale
> JaneStreet, Anyscale

- README.md
This specific google internship closed
> Google internship closed

- README.md
Updated Amazon (PHD Requirement) to reflect that the posting is no longer active.
> Mark Amazon as closed

- README.md
> Add Zoox and Rocket Labs
